### ISSUE TITLE
Recreating values when saving

### ISSUE THREAD

**Issue by misterx** [abdielcs/ExpandedCollectionBundle#1]
As example, I have a 3 entities, Post, Tag, PostsTags (with additional attributes). So when i display form, everything works fine. But if i sumbit form without changing data (in Sonata) i have next troubles:
1. Related PostsTags records are deleted (when orphan-removal="true")
2. Created new PostsTags records with same Tags/

As i see problem in this line
```php
$middle = $middleRef->newInstance();
```
https://github.com/abdielcs/ExpandedCollectionBundle/blob/master/Form/DataTransformer/MiddleClassTransformer.php#L77

PostsTags entity always is new object.

Have you any solution for this? Thanks.

**Comment by misterx** [comment]
And second one, how can I create editable PostsTags attributes for each row?

**Comment by abdielcs** [comment]
As you say the middle class reference is always a new object, so, you must validate in the controller action if all the retrieved middle objects instances (PostsTags) are already created in the database (nothing happens), or if a new instance was added (a new checkbox was checked) or if some of the instances must be deleted(one checkbox unchecked). So in the controller you must query the database for get the existent tags for this post before handle the request, then get the selected values from the form, and then decide if some actions should be take or not. The bundle simplify the forms for this situation, but the action to take depend on you. For sure your are always persist the middle instances and you shouldn't. For the second request I had no easy solution, maybe you could try put the attribute in the tag entity and then persist correctly, but is just and idea.

**Comment by abdielcs** [comment]
I will close this issue since there have been no more comments
